before:
  hooks:
    - go test ./cmd ./pkg/...
builds:
  - id: stok
    env:
    - CGO_ENABLED=0
    targets:
    - linux_amd64
  - id: stok-operator
    binary: stok-operator
    env:
    - CGO_ENABLED=0
    ldflags:
    - '-X "github.com/leg100/stok/version.Version={{ .Version }}"'
    main: ./cmd/manager/main.go
    targets:
    - linux_amd64
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
